### ISSUE TITLE
Feature: User can bet money 

### ISSUE THREAD

**Issue by AaronHe09** [AaronHe09/blackjack-game#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to bet a certain amount of money from their total amount.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to increment their bets by pressing on one of the four chips. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/AaronHe09/ajax-project/assets/79122214/44b1ea40-fba6-41ea-ba16-f0d5f3550a3c)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a heading with the content words "Place your bet"
- [x] create a container for the chip images
- [x] Insert images of the $50, $100, $200 and $500 chip images
- [x] add an attribute to each of the images to identify their amount 
- [x] Create two elements with the text content of "Money: $1000" and "Bet: $0"
- [x] Create a button with text content "Deal"
- [x] add an eventListener to the container of the chip images
   - [x] eventListener should only trigger if a image was clicked
   - [x] Increments the bet text content based on which chip was pressed
   - [x] subtracts the money amount based on which chip was pressed
