### ISSUE TITLE
Feature: User can press the deal button to start the game

### ISSUE THREAD

**Issue by AaronHe09** [AaronHe09/blackjack-game#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can press the deal button to start the game and automatically gets handed two cards

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will press the deal button and will the screen will transition to a tabel with 2 cards for both the player and the dealer 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/AaronHe09/ajax-project/assets/79122214/c852bca4-ad62-44ee-bd60-975aab15c016)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] hide the starting screen so it's not being rendered
- [x] Render the following new elements:
  - [x] money and bet that goes on the right side of the screen
  - [x] 2 columns with numbers representing the added value of the cards
  - [x] a players hand and dealers hand container for 2 cards in each column
  - [x] hit button in the first column
  - [x] stand button in the second column
  - [x] a graph button on the bottom right 
- [x] call the deck of cards api and return a full deck
- [x] draw 2 cards from the deck and assign them to the players and dealers hand containers
- [x] render the card images provided from the api to the players and dealers hand container
- [x] the dealers first card should be face down while the second card is face up
- [x] add the values of the 2 cards and render them on top of the cards for each column
