### ISSUE TITLE
Feature: User can press the hit button to get handed another card

### ISSUE THREAD

**Issue by AaronHe09** [AaronHe09/blackjack-game#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can press the hit button to get handed another card

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

when user presses the hit button they will get another card and the total amount above the card will increase based on which card was added

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/AaronHe09/ajax-project/assets/79122214/9e9b7595-fdbb-4904-96fe-d693a6f4961d)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add an eventlistener to the hit button
- [x] when the button is pressed:
  - [x] draw 1 API from the deck
  - [x] render the card image to the player's hand
  - [x] add the value of the card to the total value of the player's hand
- [x] If the value of the player's hand is equal to or greater than 21, disable the deal button
