### ISSUE TITLE
Feature: User can press the stand button to start the dealers turn and see if they won, lost or tied

### ISSUE THREAD

**Issue by AaronHe09** [AaronHe09/blackjack-game#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can press the stand button to start the dealers turn and see if they won, lost or tied

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User pressed the stand button and the deal will either hit or stand based on their total card number. they will then get a notification to show if they won or not

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-06-08 162048](https://github.com/AaronHe09/ajax-project/assets/79122214/c9f09bf4-1c09-4c2a-a8ad-464afaaabe2d)
![Screenshot 2023-06-08 162055](https://github.com/AaronHe09/ajax-project/assets/79122214/40ed774b-8004-4ae2-8821-e57157be1d89)
![Screenshot 2023-06-08 162050](https://github.com/AaronHe09/ajax-project/assets/79122214/127884fd-ca84-4ae5-aa83-25ef72000463)
![Screenshot 2023-06-08 162053](https://github.com/AaronHe09/ajax-project/assets/79122214/86955beb-5b67-4860-9026-f54a4dc7d8e9)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add an eventListner to the stand button that will :
   - [x] reveal the first card for the dealer 
   - [x] update the value of the dealers hand
   - [x] determine if the dealer should draw another card : 
      - [x] if the dealers hand value is higher than yours but less than or equal to 21, don't draw
      - [x] if the dealers hand value is lower than yours but less than 21, draw 
   - [x] create an overlay with:
     - [x] black background with .5 opacity
     - [x] should cover the whole screen
     - [x] add a text element in the middle of the overlay 
     - [x] add a hidden class to the overlay
    - [x] after the dealer is finished drawing show the results of the game : 
       - [x] if the users hand value is higher than the dealers and less or equal to 21, show YOU WIN on the overlay
       - [x] if the users hand value is equal to the dealers, show PUSH on the overlay
       - [x] if the users hand value is less than the dealers and the dealers hand is less or equal to 21, show YOU LOSE on the overlay
