### ISSUE TITLE
Feature: User can pull up a graph

### ISSUE THREAD

**Issue by AaronHe09** [AaronHe09/blackjack-game#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can pull up a graph

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can pull up a graph by pressing the graph button

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="865" alt="Screenshot 2023-06-19 223340" src="https://github.com/AaronHe09/ajax-project/assets/79122214/cccd2800-d3fb-43ee-a8cb-d7131d21b9a4">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] add a button to the bottom right corner of the screen with the text 'Graph'
- [x] in the deal button eventlistener, remove the hidden class from the graph button. 
- [x] add eventlistener for the graph button:
    - [x] create an overlay that covers the whole screen with 50% opacity 
    - [x] an image of the graph at the center 
    - [x] add an eventlistener to hide overlay when click event fires on overlay
