### ISSUE TITLE
Feature: User can play again 

### ISSUE THREAD

**Issue by AaronHe09** [AaronHe09/blackjack-game#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can play again 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
user presses play again to start playing again and be brought back to the main menu

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-06-08 162055](https://github.com/AaronHe09/ajax-project/assets/79122214/afeba621-dc83-42b1-9b33-050f99441fc5)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add a button element to the results overlay container with the text 'play again'
- [x] add an eventlistener to the button:
  - [x] update the users money based on the results of the game :
    - [x] if the player wins, multiply bet by 2 and add to money
    - [x] if they player ties, add bet to money
 - [x] update bet to 0
 - [x] if the users money is 0, reset money to 1000
  - [x] shuffle the deck
  - [x] hide the game container and show the main menu container
